[manager]
ratio = [2,3,3]
sort_by = "alphabetical"
sort_sensitive = false
sort_dir_first = true
sort_traslit = false
show_hidden = false
show_symlink = true
wrap = "no"

[opener]
pdf = [
    { run = 'okular "$0"', orphan = true, for = "unix"},
]
wpp = [
    { run = 'wpp "$0"', orphan = true, for = "unix"},
]

[open]
prepend_rules = [
    { mime = "application/pdf", use = "pdf"},
    { mime = "application/pptx", use = "wpp"}
]





