[manager]
ratio = [2,3,3]
sort_by = "extension"
sort_sensitive = true
sort_dir_first = true
sort_traslit = false
line_mode = "size_and_mtime"
show_hidden = true
show_symlink = true
wrap = "no"

[opener]
pdf = [
    { run = 'okular "$0"', orphan = true, for = "unix"},
]

[[opener.text]]
run = "'nvim \"$0\"'"


[open]
prepend_rules = [
    { mime = "application/pdf", use = "pdf"},
    { mime = "text/plain", use = "nvim"}
]





